// Code generated by xiaoyou-bilibili/xorm. DO NOT EDIT.
package query

import (
	"github.com/xiaoyou-bilibili/xorm/driver"
)

func NewQuery(db driver.DbInstance) *Query {
	return &Query{
		db:     db,
		People: NewPeople(db),
		Test:   NewTest(db),
	}
}

type Query struct {
	db     driver.DbInstance
	People people
	Test   test
}
